"""empty message

Revision ID: 267031df9df5
Revises: bb255d28530d
Create Date: 2023-11-17 08:43:25.862456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '267031df9df5'
down_revision = 'bb255d28530d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('_password_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', '_password_hash')
    # ### end Alembic commands ###
