"""fix db 2

Revision ID: 6df7f4ab2f80
Revises: 3832cc377059
Create Date: 2023-11-14 11:31:11.231662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6df7f4ab2f80'
down_revision = '3832cc377059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), nullable=True))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
