"""empty message

Revision ID: bb255d28530d
Revises: 6df7f4ab2f80
Create Date: 2023-11-17 08:40:44.968504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb255d28530d'
down_revision = '6df7f4ab2f80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
