"""empty message

Revision ID: dcb36a365f8b
Revises: 8bbd4bdd11a0
Create Date: 2024-01-11 11:01:37.522259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcb36a365f8b'
down_revision = '8bbd4bdd11a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('specializations_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_artists_specializations_id_specializations'), 'artists', 'specializations', ['specializations_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_artists_specializations_id_specializations'), 'artists', type_='foreignkey')
    op.drop_column('artists', 'specializations_id')
    # ### end Alembic commands ###
